[package]
name = "bedanno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
bio = "1.1.0"
flate2 = "1.0.26"
sorted-list = "0.2.0"
timsort = "0.1.2"
